import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../api";
import { Badge, Card, CardBody, CardHeader, EmptyState, Spinner } from "../../components/ui";
import type { JudgeRoute } from "../../types";

export default function JudgeRoutePage() {
  const [route, setRoute] = useState<JudgeRoute | null | undefined>(undefined);

  useEffect(() => {
    api<JudgeRoute | null>("/judge/route").then(setRoute);
  }, []);

  if (route === undefined) return <Spinner />;

  if (route === null) {
    return (
      <div className="space-y-6">
        <h1 className="font-display text-3xl font-bold text-maroon-700">My judging route</h1>
        <EmptyState title="No route assigned yet" hint="Routes are generated by the organizing team before presentations begin." />
      </div>
    );
  }

  const progress = route.total === 0 ? 0 : Math.round((route.visited / route.total) * 100);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="font-display text-3xl font-bold text-maroon-700">My judging route</h1>
        <Link to="/app/judge/scan" className="rounded-md bg-falcon px-4 py-2 text-sm font-bold text-white hover:bg-maroon-800">
          📷 Scan a table
        </Link>
      </div>

      <Card>
        <CardBody>
          <div className="flex items-center justify-between text-sm font-semibold">
            <span>{route.visited} of {route.total} tables visited</span>
            <span className="text-falcon">{progress}%</span>
          </div>
          <div className="mt-2 h-3 rounded-full bg-maroon-100">
            <div className="h-3 rounded-full bg-maroon-700 transition-all" style={{ width: `${progress}%` }} />
          </div>
        </CardBody>
      </Card>

      <Card>
        <CardHeader title="Route stops" subtitle="Visit tables in order — scan the table QR to check in, then score the project." />
        <CardBody className="divide-y divide-maroon-100 p-0">
          {route.stops.map((stop) => (
            <div key={stop.tableId} className="flex flex-wrap items-center gap-3 px-5 py-3">
              <span
                className={
                  "flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold " +
                  (stop.visited ? "bg-emerald-600 text-white" : "bg-maroon-100 text-maroon-700")
                }
              >
                {stop.visited ? "✓" : stop.order}
              </span>
              <div className="min-w-0 flex-1">
                <p className="font-semibold">{stop.projectTitle}</p>
                <p className="text-xs text-ink/60">
                  Table {stop.tableNumber} · {stop.zoneName}
                  {stop.track && <> · {stop.track}</>}
                </p>
              </div>
              <div className="flex items-center gap-2">
                {stop.scored ? (
                  <Badge color="green">Scored</Badge>
                ) : stop.visited ? (
                  <Badge color="sand">Needs score</Badge>
                ) : (
                  <Badge color="gray">Pending</Badge>
                )}
                {stop.projectId && (
                  <Link
                    to={`/app/judge/score/${stop.projectId}`}
                    className="rounded-md border border-maroon-700 px-3 py-1 text-xs font-bold text-maroon-700 hover:bg-maroon-50"
                  >
                    {stop.scored ? "Edit score" : "Score"}
                  </Link>
                )}
              </div>
            </div>
          ))}
        </CardBody>
      </Card>
    </div>
  );
}
